let token='',attempts=[],aid='';const $=x=>document.getElementById(x),cfg=()=>window.GRAMMAR_CONFIG||{};
async function api(path,method='GET',body=null){let c=cfg(),r=await fetch(c.SUPABASE_URL+path,{method,headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,Authorization:'Bearer '+(token||c.SUPABASE_PUBLISHABLE_KEY),'Content-Type':'application/json'},body:body?JSON.stringify(body):null}),t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):null}
const rpc=(fn,b={})=>api('/rest/v1/rpc/'+fn,'POST',b);
async function signIn(){try{let c=cfg(),r=await fetch(c.SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})}),d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||'Sign-in failed');token=d.access_token;sessionStorage.setItem('gt',token);$('login').hidden=true;$('dash').hidden=false;load()}catch(e){$('loginerr').textContent='Could not sign in.'}}
function signOut(){sessionStorage.removeItem('gt');location.reload()}
async function load(){try{let a=await api('/rest/v1/assessments?select=id&is_active=eq.true&order=created_at.desc&limit=1');aid=a?.[0]?.id||'';await loadAttempts();await loadTimer()}catch(e){alert('Dashboard: '+e.message)}}
async function loadAttempts(){attempts=await rpc('teacher_dashboard_attempts');renderAttempts();let n=attempts.length,avg=n?attempts.reduce((s,x)=>s+Number(x.percentage||0),0)/n:0,tm=n?attempts.reduce((s,x)=>s+Number(x.duration_seconds||0),0)/n:0,students=new Set(attempts.map(x=>x.student_id)).size;$('metrics').innerHTML=[['Students',students],['Submitted',n],['Average',avg.toFixed(1)+'%'],['Avg time',fmt(tm)]].map(x=>'<div class="card metric"><span class="tag">'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('')}
function renderAttempts(){let g=$('groupfilter').value,rows=attempts.filter(x=>!g||x.group_code===g);$('attempts').innerHTML=rows.map(x=>'<tr><td><b>'+esc(x.full_name)+'</b></td><td>'+esc(x.group_code)+'</td><td>'+esc(x.topic_number)+'</td><td>'+esc(x.score)+' / '+esc(x.max_score)+'</td><td><span class="pill">'+esc(x.percentage)+'%</span></td><td>'+fmt(x.duration_seconds)+'</td><td>'+new Date(x.submitted_at).toLocaleString()+'</td></tr>').join('')||'<tr><td colspan="7" class="muted">No submitted attempts yet.</td></tr>'}
async function loadTimer(){if(!aid)return $('timerstate').textContent='No active assessment.';let d=await rpc('get_assessment_timer',{p_assessment_id:aid}),x=Array.isArray(d)?d[0]:d;if(x){$('minutes').value=x.time_limit_minutes;$('timerstate').textContent='Base '+x.time_limit_minutes+' min · extra '+Math.round(Number(x.time_adjustment_seconds||0)/60)+' min'}}
async function setLimit(){try{await rpc('teacher_set_time_limit',{p_assessment_id:aid,p_minutes:Number($('minutes').value)});loadTimer()}catch(e){alert(e.message)}}
async function addTime(s){try{await rpc('teacher_add_time',{p_assessment_id:aid,p_seconds:s});loadTimer()}catch(e){alert(e.message)}}
async function resetExtra(){try{await rpc('teacher_reset_extra_time',{p_assessment_id:aid});loadTimer()}catch(e){alert(e.message)}}
function fmt(s){s=Math.round(Number(s||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
addEventListener('DOMContentLoaded',()=>{token=sessionStorage.getItem('gt')||'';if(token){$('login').hidden=true;$('dash').hidden=false;load()}});Object.assign(window,{signIn,signOut,setLimit,addTime,resetExtra,renderAttempts});