let token='',attempts=[],skills=[],aid='',timerPoll=null;const $=x=>document.getElementById(x),cfg=()=>window.GRAMMAR_CONFIG||{};async function api(path,method='GET',body=null,useAuth=true){let c=cfg(),r=await fetch(c.SUPABASE_URL+path,{method,headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,Authorization:'Bearer '+(useAuth&&token?token:c.SUPABASE_PUBLISHABLE_KEY),'Content-Type':'application/json'},body:body?JSON.stringify(body):null}),t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):null}const rpc=(fn,b={},useAuth=true)=>api('/rest/v1/rpc/'+fn,'POST',b,useAuth);
async function signIn(){let b=$('signinbtn'),err=$('loginerr');err.textContent='';b.disabled=true;try{let c=cfg(),r=await fetch(c.SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})}),d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||d.message||'Sign-in failed');token=d.access_token;sessionStorage.setItem('gt',token);$('login').hidden=true;$('dash').hidden=false;await load()}catch(e){err.textContent=e.message;b.disabled=false}}
function signOut(){if(timerPoll)clearInterval(timerPoll);sessionStorage.removeItem('gt');location.reload()}async function resolveAssessment(){let d=await rpc('get_active_assessment',{p_topic_number:1},false),row=Array.isArray(d)?d[0]:d;aid=String(row?.assessment_id||row?.id||'').trim();if(!aid)throw Error('Assessment not found')}
async function load(){try{await resolveAssessment();let res=await Promise.all([rpc('teacher_dashboard_attempts'),rpc('teacher_skill_summary').catch(()=>[]),loadTimer()]);attempts=Array.isArray(res[0])?res[0]:[];skills=Array.isArray(res[1])?res[1]:[];renderAll();if(timerPoll)clearInterval(timerPoll);timerPoll=setInterval(()=>loadTimer(true),10000)}catch(e){alert('Dashboard: '+e.message)}}
function renderAll(){renderAttempts();renderMetrics(attempts);renderGroups();renderStudents();renderTopics();renderSkills()}
function renderMetrics(rows){let n=rows.length,avg=n?rows.reduce((s,x)=>s+Number(x.percentage||0),0)/n:0,tm=n?rows.reduce((s,x)=>s+Number(x.duration_seconds||0),0)/n:0,students=new Set(rows.map(x=>x.student_id)).size;$('metrics').innerHTML=[['Students',students],['Submitted',n],['Average',avg.toFixed(1)+'%'],['Avg time',fmt(tm)]].map(x=>'<div class="card metric"><span class="tag">'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('')}
function renderAttempts(){let g=$('groupfilter')?.value||'',rows=attempts.filter(x=>!g||x.group_code===g);$('attempts').innerHTML=rows.map(x=>'<tr class="clickrow" onclick="openStudent(\''+escjs(x.student_id)+'\')"><td><b>'+esc(x.full_name)+'</b></td><td>'+esc(x.group_code)+'</td><td>'+esc(x.topic_number)+'</td><td>'+esc(x.score)+' / '+esc(x.max_score)+'</td><td><span class="pill">'+esc(x.percentage)+'%</span></td><td>'+fmt(x.duration_seconds)+'</td><td>'+new Date(x.submitted_at).toLocaleString()+'</td></tr>').join('')||'<tr><td colspan="7" class="muted">No submitted attempts yet.</td></tr>';renderMetrics(rows)}
function renderGroups(){let groups=['150','151','154'];$('groupsgrid').innerHTML=groups.map(g=>{let r=attempts.filter(x=>x.group_code===g),students=new Set(r.map(x=>x.student_id)).size,avg=r.length?r.reduce((s,x)=>s+Number(x.percentage||0),0)/r.length:0;return '<article class="card clickrow" onclick="openGroup(\''+g+'\')"><span class="tag">Group '+g+'</span><h2>'+students+' students</h2><p>'+r.length+' submitted · average <b>'+avg.toFixed(1)+'%</b></p><div class="scorebar"><span style="width:'+Math.min(100,avg)+'%"></span></div></article>'}).join('')}
function studentData(){let m={};attempts.forEach(x=>{let k=x.student_id||(x.full_name+'|'+x.group_code);(m[k]??={id:x.student_id,name:x.full_name,group:x.group_code,rows:[]}).rows.push(x)});return Object.values(m)}
function renderStudents(){let g=$('studentgroup')?.value||'',ss=studentData().filter(s=>!g||s.group===g).sort((a,b)=>a.name.localeCompare(b.name));$('studentrows').innerHTML=ss.map(s=>{let avg=s.rows.reduce((n,x)=>n+Number(x.percentage||0),0)/s.rows.length,latest=[...s.rows].sort((a,b)=>new Date(b.submitted_at)-new Date(a.submitted_at))[0];return '<tr class="clickrow" onclick="openStudent(\''+escjs(s.id)+'\')"><td><b>'+esc(s.name)+'</b></td><td>'+esc(s.group)+'</td><td>'+s.rows.length+'</td><td>'+avg.toFixed(1)+'%</td><td>'+Number(latest.percentage||0).toFixed(1)+'%</td></tr>'}).join('')||'<tr><td colspan="5">No students yet.</td></tr>'}
function renderTopics(){let avg=attempts.length?attempts.reduce((s,x)=>s+Number(x.percentage||0),0)/attempts.length:0;$('topicstats').innerHTML='<b>'+attempts.length+'</b> submissions · <b>'+new Set(attempts.map(x=>x.student_id)).size+'</b> students · average <b>'+avg.toFixed(1)+'%</b>';$('topicbar').style.width=Math.min(100,avg)+'%'}
function renderSkills(){if(!skills.length){$('skillslist').innerHTML='<section class="card muted">Skill analytics will appear after submitted answers are available.</section>';return}let m={};skills.forEach(x=>{let k=x.skill_code||x.skill_title;(m[k]??={title:x.skill_title||k,ref:x.textbook_reference,correct:0,total:0}).correct+=Number(x.correct_questions||0);m[k].total+=Number(x.total_questions||0)});let a=Object.values(m).map(x=>({...x,p:x.total?100*x.correct/x.total:0})).sort((a,b)=>a.p-b.p);$('skillslist').innerHTML=a.map(x=>'<article class="card"><span class="tag">'+x.p.toFixed(0)+'% correct</span><h3>'+esc(x.title)+'</h3><div class="scorebar"><span style="width:'+x.p+'%"></span></div>'+(x.ref?'<p class="muted">Revise: '+esc(x.ref)+'</p>':'')+'</article>').join('')}
function openGroup(g){showTab('students');$('studentgroup').value=g;renderStudents()}function openStudent(id){let s=studentData().find(x=>String(x.id)===String(id));if(!s)return;showTab('students');$('studentgroup').value=s.group;renderStudents();setTimeout(()=>alert(s.name+' · Group '+s.group+'\n'+s.rows.length+' submitted attempt(s).\n\nNext step: detailed question-by-question review.'),20)}
async function loadTimer(silent=false){try{if(!aid)await resolveAssessment();let d=await rpc('get_assessment_timer',{p_assessment_id:aid},false),x=Array.isArray(d)?d[0]:d;if(!x)return;let base=Number(x.time_limit_minutes||0),extra=Number(x.time_adjustment_seconds||0);$('minutes').value=base;$('timerstate').textContent='Base '+base+' min · extra '+Math.round(extra/60)+' min';$('liveclock').textContent=fmt(base*60+extra);$('livemeta').textContent=base+' min base · '+(extra?'+'+Math.round(extra/60)+' min extra':'no extra time');$('lastsync').textContent='Synced '+new Date().toLocaleTimeString()}catch(e){if(!silent)throw e}}
async function timerAction(fn,payload){try{await rpc(fn,{p_assessment_id:aid,...payload});await loadTimer()}catch(e){alert('Timer: '+e.message)}}async function setBase(v){v=Number(v);if(v<1||v>240)return; $('minutes').value=v;await timerAction('teacher_set_time_limit',{p_minutes:v})}const setLimit=()=>setBase($('minutes').value),addTime=s=>timerAction('teacher_add_time',{p_seconds:s}),resetExtra=()=>timerAction('teacher_reset_extra_time',{});
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));['overview','groups','students','topics','skills'].forEach(x=>$('view-'+x).hidden=x!==tab)}function fmt(s){s=Math.max(0,Math.round(Number(s||0)));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escjs(s){return String(s??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
addEventListener('DOMContentLoaded',()=>{$('loginform')?.addEventListener('submit',e=>{e.preventDefault();signIn()});document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));token=sessionStorage.getItem('gt')||'';if(token){$('login').hidden=true;$('dash').hidden=false;load()}});Object.assign(window,{signIn,signOut,setLimit,setBase,addTime,resetExtra,renderAttempts,renderStudents,showTab,openGroup,openStudent});