let token='',attempts=[],aid='',activeTab='overview';const $=x=>document.getElementById(x),cfg=()=>window.GRAMMAR_CONFIG||{};
async function api(path,method='GET',body=null,useAuth=true){let c=cfg(),r=await fetch(c.SUPABASE_URL+path,{method,headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,Authorization:'Bearer '+(useAuth&&token?token:c.SUPABASE_PUBLISHABLE_KEY),'Content-Type':'application/json'},body:body?JSON.stringify(body):null}),t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):null}
const rpc=(fn,b={},useAuth=true)=>api('/rest/v1/rpc/'+fn,'POST',b,useAuth);
async function signIn(){let b=$('signinbtn'),err=$('loginerr');err.textContent='';b.disabled=true;b.textContent='Signing in…';try{let c=cfg(),r=await fetch(c.SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:c.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})}),d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||d.message||'Sign-in failed');token=d.access_token;sessionStorage.setItem('gt',token);$('login').hidden=true;$('dash').hidden=false;await load()}catch(e){err.textContent=e.message||'Could not sign in.';$('dash').hidden=true;$('login').hidden=false;b.disabled=false;b.textContent='Sign in'}}
function signOut(){sessionStorage.removeItem('gt');location.reload()}
async function resolveAssessment(){let d=await rpc('get_active_assessment',{p_topic_number:1},false);let row=Array.isArray(d)?d[0]:d;aid=String(row?.assessment_id||row?.id||'').trim();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(aid))throw Error('Topic 1 assessment ID was not returned.');return aid}
async function load(){try{await resolveAssessment();await Promise.all([loadAttempts(),loadTimer()]);showTab('overview')}catch(e){$('timerstate').textContent='Dashboard setup error: '+e.message;console.error(e)}}
async function loadAttempts(){let d=await rpc('teacher_dashboard_attempts');attempts=Array.isArray(d)?d:[];renderAttempts();let n=attempts.length,avg=n?attempts.reduce((s,x)=>s+Number(x.percentage||0),0)/n:0,tm=n?attempts.reduce((s,x)=>s+Number(x.duration_seconds||0),0)/n:0,students=new Set(attempts.map(x=>x.student_id)).size;$('metrics').innerHTML=[['Students',students],['Submitted',n],['Average',avg.toFixed(1)+'%'],['Avg time',fmt(tm)]].map(x=>'<div class="card metric"><span class="tag">'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('')}
function renderAttempts(){let g=$('groupfilter')?.value||'',rows=attempts.filter(x=>!g||x.group_code===g);$('attempts').innerHTML=rows.map(x=>'<tr><td><b>'+esc(x.full_name)+'</b></td><td>'+esc(x.group_code)+'</td><td>'+esc(x.topic_number)+'</td><td>'+esc(x.score)+' / '+esc(x.max_score)+'</td><td><span class="pill">'+esc(x.percentage)+'%</span></td><td>'+fmt(x.duration_seconds)+'</td><td>'+new Date(x.submitted_at).toLocaleString()+'</td></tr>').join('')||'<tr><td colspan="7" class="muted">No submitted attempts yet.</td></tr>'}
async function ensureAid(){if(!aid)await resolveAssessment();return aid}
async function loadTimer(){await ensureAid();let d=await rpc('get_assessment_timer',{p_assessment_id:aid},false),x=Array.isArray(d)?d[0]:d;if(!x)throw Error('Timer settings were not returned.');$('minutes').value=x.time_limit_minutes;$('timerstate').textContent='Base '+x.time_limit_minutes+' min · extra '+Math.round(Number(x.time_adjustment_seconds||0)/60)+' min'}
async function timerAction(fn,payload){try{await ensureAid();await rpc(fn,{p_assessment_id:aid,...payload});await loadTimer()}catch(e){alert('Timer: '+e.message)}}
const setLimit=()=>timerAction('teacher_set_time_limit',{p_minutes:Number($('minutes').value)}),addTime=s=>timerAction('teacher_add_time',{p_seconds:s}),resetExtra=()=>timerAction('teacher_reset_extra_time',{});
function showTab(tab){activeTab=tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));let note=$('tabnote');if(!note)return;if(tab==='overview'){note.hidden=true;return}let labels={groups:'Groups view is next: group-level results and live progress.',students:'Students view is next: individual history across topics.',topics:'Topics view is next: assessments, time limits and topic progress.',skills:'Skills view is next: weak areas and textbook references.'};note.textContent=labels[tab]||'';note.hidden=false}
function fmt(s){s=Math.round(Number(s||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
addEventListener('DOMContentLoaded',()=>{let f=$('loginform');if(f)f.addEventListener('submit',e=>{e.preventDefault();signIn()});document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));token=sessionStorage.getItem('gt')||'';if(token){$('login').hidden=true;$('dash').hidden=false;load()}});Object.assign(window,{signIn,signOut,setLimit,addTime,resetExtra,renderAttempts,showTab});